// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 07:21 on Wednesday, 19 November 2025.
	/// </remarks>
	public partial class Model_VMP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Field backing the a property</summary>
		private double a_field;
		/// <summary>Field backing the b property</summary>
		private double b_field;
		/// <summary>True if Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth has executed. Set this to false to force re-execution of Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth</summary>
		public bool Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone;
		/// <summary>True if Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12 has executed. Set this to false to force re-execution of Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12</summary>
		public bool Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone;
		/// <summary>True if Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12 has performed initialisation. Set this to false to force re-execution of Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12</summary>
		public bool Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised;
		/// <summary>True if Changed_a_b_numberOfBases_numberOfSignals has executed. Set this to false to force re-execution of Changed_a_b_numberOfBases_numberOfSignals</summary>
		public bool Changed_a_b_numberOfBases_numberOfSignals_isDone;
		/// <summary>True if Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11 has executed. Set this to false to force re-execution of Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11</summary>
		public bool Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isDone;
		/// <summary>True if Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11 has performed initialisation. Set this to false to force re-execution of Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11</summary>
		public bool Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised;
		/// <summary>True if Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13 has executed. Set this to false to force re-execution of Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13</summary>
		public bool Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone;
		/// <summary>True if Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13 has performed initialisation. Set this to false to force re-execution of Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13</summary>
		public bool Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised;
		/// <summary>True if Changed_numberOfBases has executed. Set this to false to force re-execution of Changed_numberOfBases</summary>
		public bool Changed_numberOfBases_isDone;
		/// <summary>True if Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7 has executed. Set this to false to force re-execution of Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7</summary>
		public bool Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone;
		/// <summary>True if Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7 has performed initialisation. Set this to false to force re-execution of Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7</summary>
		public bool Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised;
		/// <summary>True if Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3 has executed. Set this to false to force re-execution of Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3</summary>
		public bool Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone;
		/// <summary>True if Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3 has performed initialisation. Set this to false to force re-execution of Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3</summary>
		public bool Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised;
		/// <summary>True if Changed_numberOfBases_numberOfSignals has executed. Set this to false to force re-execution of Changed_numberOfBases_numberOfSignals</summary>
		public bool Changed_numberOfBases_numberOfSignals_isDone;
		/// <summary>True if Changed_numberOfBases_signalWidth has executed. Set this to false to force re-execution of Changed_numberOfBases_signalWidth</summary>
		public bool Changed_numberOfBases_signalWidth_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0</summary>
		public bool Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0</summary>
		public bool Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9</summary>
		public bool Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9</summary>
		public bool Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised;
		/// <summary>True if Changed_numberOfSignals_signalWidth has executed. Set this to false to force re-execution of Changed_numberOfSignals_signalWidth</summary>
		public bool Changed_numberOfSignals_signalWidth_isDone;
		public DistributionStructArray2D<Gaussian,double> clean_B;
		public Gamma coefficientPrecisions_F_reduced;
		/// <summary>Message to marginal of 'coefficientPrecisions'</summary>
		public DistributionStructArray2D<Gamma,double> coefficientPrecisions_marginal_F;
		/// <summary>Message from use of 'coefficientPrecisions'</summary>
		public DistributionStructArray2D<Gamma,double> coefficientPrecisions_use_B;
		public DistributionStructArray2D<Gaussian,double> coefficients_F;
		/// <summary>Message to marginal of 'coefficients'</summary>
		public DistributionStructArray2D<Gaussian,double> coefficients_marginal_F;
		/// <summary>Message from use of 'coefficients'</summary>
		public DistributionStructArray2D<Gaussian,double> coefficients_use_B;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		public DistributionStructArray2D<Gaussian,double> dictionary_F;
		/// <summary>Message to marginal of 'dictionary'</summary>
		public DistributionStructArray2D<Gaussian,double> dictionary_marginal_F;
		/// <summary>Message from use of 'dictionary'</summary>
		public DistributionStructArray2D<Gaussian,double> dictionary_use_B;
		public Gaussian dictionaryMeans_F_reduced;
		/// <summary>Message to marginal of 'dictionaryMeans'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> dictionaryMeans_marginal_F;
		/// <summary>Message from use of 'dictionaryMeans'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> dictionaryMeans_use_B;
		public Gamma dictionaryPrecisions_F_reduced;
		/// <summary>Message to marginal of 'dictionaryPrecisions'</summary>
		public DistributionStructArray2D<Gamma,double> dictionaryPrecisions_marginal_F;
		/// <summary>Message from use of 'dictionaryPrecisions'</summary>
		public DistributionStructArray2D<Gamma,double> dictionaryPrecisions_use_B;
		/// <summary>Message to marginal of 'noisePrecision'</summary>
		public Gamma noisePrecision_marginal_F;
		/// <summary>Message from use of 'noisePrecision'</summary>
		public Gamma noisePrecision_use_B;
		/// <summary>Field backing the noisePrecisionPrior property</summary>
		private Gamma noisePrecisionPrior_field;
		/// <summary>Field backing the numberOfBases property</summary>
		private int numberOfBases_field;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the numberOfSignals property</summary>
		private int numberOfSignals_field;
		/// <summary>Field backing the signals property</summary>
		private double[,] signals_field;
		/// <summary>Field backing the signalWidth property</summary>
		private int signalWidth_field;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'a'</summary>
		public double a
		{
			get {
				return this.a_field;
			}
			set {
				if (this.a_field!=value) {
					this.a_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = false;
					this.Changed_a_b_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'b'</summary>
		public double b
		{
			get {
				return this.b_field;
			}
			set {
				if (this.b_field!=value) {
					this.b_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = false;
					this.Changed_a_b_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'noisePrecisionPrior'</summary>
		public Gamma noisePrecisionPrior
		{
			get {
				return this.noisePrecisionPrior_field;
			}
			set {
				if (this.noisePrecisionPrior_field!=value) {
					this.noisePrecisionPrior_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isDone = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'numberOfBases'</summary>
		public int numberOfBases
		{
			get {
				return this.numberOfBases_field;
			}
			set {
				if (this.numberOfBases_field!=value) {
					this.numberOfBases_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = false;
					this.Changed_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = false;
					this.Changed_numberOfBases_isDone = false;
					this.Changed_numberOfBases_signalWidth_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'numberOfSignals'</summary>
		public int numberOfSignals
		{
			get {
				return this.numberOfSignals_field;
			}
			set {
				if (this.numberOfSignals_field!=value) {
					this.numberOfSignals_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfSignals_signalWidth_isDone = false;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone = false;
					this.Changed_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfSignals_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'signals'</summary>
		public double[,] signals
		{
			get {
				return this.signals_field;
			}
			set {
				if ((value!=null)&&((value.GetLength(0)!=this.numberOfSignals)||(value.GetLength(1)!=this.signalWidth))) {
					throw new ArgumentException(((("Provided array of size "+(((("("+value.GetLength(0))+",")+value.GetLength(1))+")"))+" when size ")+(((("("+this.numberOfSignals)+",")+this.signalWidth)+")"))+" was expected");
				}
				this.signals_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = false;
				this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = false;
				this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised = false;
				this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
				this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
				this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = false;
				this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'signalWidth'</summary>
		public int signalWidth
		{
			get {
				return this.signalWidth_field;
			}
			set {
				if (this.signalWidth_field!=value) {
					this.signalWidth_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfSignals_signalWidth_isDone = false;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised = false;
					this.Changed_numberOfBases_signalWidth_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = false;
					this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
				}
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of a and b and noisePrecisionPrior and numberOfBases and numberOfIterations and numberOfSignals and signals and signalWidth</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth(int numberOfIterations)
		{
			if (this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone) {
				return ;
			}
			DistributionStructArray2D<Gaussian,double> clean_F;
			// Create array for 'clean' Forwards messages.
			clean_F = new DistributionStructArray2D<Gaussian,double>(this.numberOfSignals, this.signalWidth);
			for(int _ind0 = 0; _ind0<this.numberOfSignals; _ind0++) {
				for(int _ind1 = 0; _ind1<this.signalWidth; _ind1++) {
					clean_F[_ind0, _ind1] = Gaussian.Uniform();
				}
			}
			// Create array for replicates of 'noisePrecision_rep_rep_B'
			Gamma[][] noisePrecision_rep_rep_B = new Gamma[this.numberOfSignals][];
			for(int signal = 0; signal<this.numberOfSignals; signal++) {
				// Create array for 'noisePrecision_rep_rep' Backwards messages.
				noisePrecision_rep_rep_B[signal] = new Gamma[this.signalWidth];
			}
			for(int sample = 0; sample<this.signalWidth; sample++) {
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					noisePrecision_rep_rep_B[signal][sample] = Gamma.Uniform();
				}
			}
			Gamma[] noisePrecision_rep_B;
			// Create array for 'noisePrecision_rep' Backwards messages.
			noisePrecision_rep_B = new Gamma[this.numberOfSignals];
			for(int signal = 0; signal<this.numberOfSignals; signal++) {
				noisePrecision_rep_B[signal] = Gamma.Uniform();
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int basis = 0; basis<this.numberOfBases; basis++) {
					for(int sample = 0; sample<this.signalWidth; sample++) {
						// Message to 'dictionaryMeans_marginal' from Variable factor
						this.dictionaryMeans_marginal_F[basis][sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.dictionaryMeans_use_B[basis][sample], this.dictionaryMeans_F_reduced, this.dictionaryMeans_marginal_F[basis][sample]);
						// Message to 'dictionaryPrecisions_use' from Gaussian factor
						this.dictionaryPrecisions_use_B[basis, sample] = GaussianOp.PrecisionAverageLogarithm(this.dictionary_marginal_F[basis, sample], this.dictionaryMeans_marginal_F[basis][sample]);
						// Message to 'dictionaryPrecisions_marginal' from Variable factor
						this.dictionaryPrecisions_marginal_F[basis, sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.dictionaryPrecisions_use_B[basis, sample], this.dictionaryPrecisions_F_reduced, this.dictionaryPrecisions_marginal_F[basis, sample]);
						// Message to 'dictionary' from Gaussian factor
						this.dictionary_F[basis, sample] = GaussianOp.SampleAverageLogarithm(this.dictionaryMeans_marginal_F[basis][sample], this.dictionaryPrecisions_marginal_F[basis, sample]);
						// Message to 'dictionary_marginal' from Variable factor
						this.dictionary_marginal_F[basis, sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.dictionary_use_B[basis, sample], this.dictionary_F[basis, sample], this.dictionary_marginal_F[basis, sample]);
						// Message to 'dictionaryMeans_use' from Gaussian factor
						this.dictionaryMeans_use_B[basis][sample] = GaussianOp.MeanAverageLogarithm(this.dictionary_marginal_F[basis, sample], this.dictionaryPrecisions_marginal_F[basis, sample]);
					}
				}
				// Message to 'coefficients_use' from MatrixMultiply factor
				this.coefficients_use_B = MatrixMultiplyOp.AAverageLogarithm(this.clean_B, this.coefficients_marginal_F, this.dictionary_marginal_F, this.coefficients_use_B);
				for(int basis = 0; basis<this.numberOfBases; basis++) {
					for(int signal = 0; signal<this.numberOfSignals; signal++) {
						// Message to 'coefficientPrecisions_marginal' from Variable factor
						this.coefficientPrecisions_marginal_F[signal, basis] = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.coefficientPrecisions_use_B[signal, basis], this.coefficientPrecisions_F_reduced, this.coefficientPrecisions_marginal_F[signal, basis]);
						// Message to 'coefficients' from Gaussian factor
						this.coefficients_F[signal, basis] = GaussianOp.SampleAverageLogarithm(0.0, this.coefficientPrecisions_marginal_F[signal, basis]);
						// Message to 'coefficients_marginal' from Variable factor
						this.coefficients_marginal_F[signal, basis] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.coefficients_use_B[signal, basis], this.coefficients_F[signal, basis], this.coefficients_marginal_F[signal, basis]);
					}
				}
				// Message to 'clean' from MatrixMultiply factor
				clean_F = MatrixMultiplyOp.MatrixMultiplyAverageLogarithm(this.coefficients_marginal_F, this.dictionary_marginal_F, clean_F);
				for(int sample = 0; sample<this.signalWidth; sample++) {
					for(int signal = 0; signal<this.numberOfSignals; signal++) {
						// Message to 'noisePrecision_rep_rep' from Gaussian factor
						noisePrecision_rep_rep_B[signal][sample] = GaussianOp.PrecisionAverageLogarithm(this.signals[signal, sample], clean_F[signal, sample]);
					}
				}
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					// Message to 'noisePrecision_rep' from Replicate factor
					noisePrecision_rep_B[signal] = ReplicateOp.DefAverageLogarithm<Gamma>(noisePrecision_rep_rep_B[signal], noisePrecision_rep_B[signal]);
				}
				// Message to 'noisePrecision_use' from Replicate factor
				this.noisePrecision_use_B = ReplicateOp.DefAverageLogarithm<Gamma>(noisePrecision_rep_B, this.noisePrecision_use_B);
				// Message to 'noisePrecision_marginal' from Variable factor
				this.noisePrecision_marginal_F = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.noisePrecision_use_B, this.noisePrecisionPrior, this.noisePrecision_marginal_F);
				for(int sample = 0; sample<this.signalWidth; sample++) {
					for(int signal = 0; signal<this.numberOfSignals; signal++) {
						// Message to 'clean' from Gaussian factor
						this.clean_B[signal, sample] = GaussianOp.MeanAverageLogarithm(this.signals[signal, sample], this.noisePrecision_marginal_F);
					}
				}
				// Message to 'dictionary_use' from MatrixMultiply factor
				this.dictionary_use_B = MatrixMultiplyOp.BAverageLogarithm(this.clean_B, this.coefficients_marginal_F, this.dictionary_marginal_F, this.dictionary_use_B);
				for(int basis = 0; basis<this.numberOfBases; basis++) {
					for(int signal = 0; signal<this.numberOfSignals; signal++) {
						// Message to 'coefficientPrecisions_use' from Gaussian factor
						this.coefficientPrecisions_use_B[signal, basis] = GaussianOp.PrecisionAverageLogarithm(this.coefficients_marginal_F[signal, basis], 0.0);
					}
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			// Message to 'coefficients_use' from MatrixMultiply factor
			this.coefficients_use_B = MatrixMultiplyOp.AAverageLogarithm(this.clean_B, this.coefficients_marginal_F, this.dictionary_marginal_F, this.coefficients_use_B);
			for(int basis = 0; basis<this.numberOfBases; basis++) {
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					// Message to 'coefficients_marginal' from Variable factor
					this.coefficients_marginal_F[signal, basis] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.coefficients_use_B[signal, basis], this.coefficients_F[signal, basis], this.coefficients_marginal_F[signal, basis]);
				}
				for(int sample = 0; sample<this.signalWidth; sample++) {
					// Message to 'dictionaryMeans_marginal' from Variable factor
					this.dictionaryMeans_marginal_F[basis][sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.dictionaryMeans_use_B[basis][sample], this.dictionaryMeans_F_reduced, this.dictionaryMeans_marginal_F[basis][sample]);
				}
			}
			this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of a and b and numberOfBases and numberOfIterationsDecreased and numberOfSignals and must reset on changes to noisePrecisionPrior and signals and signalWidth</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12(bool initialise)
		{
			if (this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone&&((!initialise)||this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised)) {
				return ;
			}
			for(int basis = 0; basis<this.numberOfBases; basis++) {
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					// Message to 'coefficientPrecisions_marginal' from Variable factor
					this.coefficientPrecisions_marginal_F[signal, basis] = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.coefficientPrecisions_use_B[signal, basis], this.coefficientPrecisions_F_reduced, this.coefficientPrecisions_marginal_F[signal, basis]);
					// Message to 'coefficients' from Gaussian factor
					this.coefficients_F[signal, basis] = GaussianOp.SampleAverageLogarithm(0.0, this.coefficientPrecisions_marginal_F[signal, basis]);
					// Message to 'coefficients_marginal' from Variable factor
					this.coefficients_marginal_F[signal, basis] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.coefficients_use_B[signal, basis], this.coefficients_F[signal, basis], this.coefficients_marginal_F[signal, basis]);
				}
			}
			this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = true;
			this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of a and b and numberOfBases and numberOfSignals</summary>
		private void Changed_a_b_numberOfBases_numberOfSignals()
		{
			if (this.Changed_a_b_numberOfBases_numberOfSignals_isDone) {
				return ;
			}
			if (this.numberOfSignals>0) {
				if (this.numberOfBases>0) {
					// Message to 'coefficientPrecisions' from GammaFromShapeAndRate factor
					this.coefficientPrecisions_F_reduced = GammaFromShapeAndRateOpBase.SampleAverageLogarithm(this.a, this.b);
				}
			}
			this.Changed_a_b_numberOfBases_numberOfSignals_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of noisePrecisionPrior and numberOfIterationsDecreased and must reset on changes to a and b and numberOfBases and numberOfSignals and signals and signalWidth</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11(bool initialise)
		{
			if (this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isDone&&((!initialise)||this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised)) {
				return ;
			}
			// Message to 'noisePrecision_marginal' from Variable factor
			this.noisePrecision_marginal_F = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.noisePrecision_use_B, this.noisePrecisionPrior, this.noisePrecision_marginal_F);
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isDone = true;
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of noisePrecisionPrior and numberOfIterationsDecreased and numberOfSignals and signals and signalWidth and must reset on changes to a and b and numberOfBases</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13(bool initialise)
		{
			if (this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone&&((!initialise)||this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised)) {
				return ;
			}
			for(int sample = 0; sample<this.signalWidth; sample++) {
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					// Message to 'clean' from Gaussian factor
					this.clean_B[signal, sample] = GaussianOp.MeanAverageLogarithm(this.signals[signal, sample], this.noisePrecision_marginal_F);
				}
			}
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = true;
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfBases</summary>
		private void Changed_numberOfBases()
		{
			if (this.Changed_numberOfBases_isDone) {
				return ;
			}
			// Create array for 'dictionaryMeans_use' Backwards messages.
			this.dictionaryMeans_use_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.numberOfBases);
			// Create array for 'dictionaryMeans_marginal' Forwards messages.
			this.dictionaryMeans_marginal_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.numberOfBases);
			this.Changed_numberOfBases_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfBases and numberOfIterationsDecreased and numberOfSignals and must reset on changes to a and b and noisePrecisionPrior and signals and signalWidth</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7(bool initialise)
		{
			if (this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone&&((!initialise)||this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised)) {
				return ;
			}
			for(int basis = 0; basis<this.numberOfBases; basis++) {
				for(int signal = 0; signal<this.numberOfSignals; signal++) {
					this.coefficientPrecisions_use_B[signal, basis] = Gamma.Uniform();
					this.coefficientPrecisions_marginal_F[signal, basis] = Gamma.Uniform();
					this.coefficients_F[signal, basis] = Gaussian.Uniform();
					this.coefficients_use_B[signal, basis] = Gaussian.Uniform();
					this.coefficients_marginal_F[signal, basis] = Gaussian.Uniform();
				}
			}
			this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone = true;
			this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfBases and numberOfIterationsDecreased and signalWidth and must reset on changes to a and b and noisePrecisionPrior and numberOfSignals and signals</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3(bool initialise)
		{
			if (this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone&&((!initialise)||this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised)) {
				return ;
			}
			for(int basis = 0; basis<this.numberOfBases; basis++) {
				for(int sample = 0; sample<this.signalWidth; sample++) {
					this.dictionaryPrecisions_use_B[basis, sample] = Gamma.Uniform();
					this.dictionaryPrecisions_marginal_F[basis, sample] = Gamma.Uniform();
					this.dictionaryMeans_use_B[basis][sample] = Gaussian.Uniform();
					this.dictionaryMeans_marginal_F[basis][sample] = Gaussian.Uniform();
					this.dictionary_F[basis, sample] = Gaussian.Uniform();
					this.dictionary_use_B[basis, sample] = Gaussian.Uniform();
					this.dictionary_marginal_F[basis, sample] = Gaussian.Uniform();
					// Message to 'dictionaryMeans_marginal' from Variable factor
					this.dictionaryMeans_marginal_F[basis][sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.dictionaryMeans_use_B[basis][sample], this.dictionaryMeans_F_reduced, this.dictionaryMeans_marginal_F[basis][sample]);
					// Message to 'dictionaryPrecisions_marginal' from Variable factor
					this.dictionaryPrecisions_marginal_F[basis, sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gamma>(this.dictionaryPrecisions_use_B[basis, sample], this.dictionaryPrecisions_F_reduced, this.dictionaryPrecisions_marginal_F[basis, sample]);
					// Message to 'dictionary' from Gaussian factor
					this.dictionary_F[basis, sample] = GaussianOp.SampleAverageLogarithm(this.dictionaryMeans_marginal_F[basis][sample], this.dictionaryPrecisions_marginal_F[basis, sample]);
					// Message to 'dictionary_marginal' from Variable factor
					this.dictionary_marginal_F[basis, sample] = VariableVmpOp<double>.MarginalAverageLogarithm<Gaussian>(this.dictionary_use_B[basis, sample], this.dictionary_F[basis, sample], this.dictionary_marginal_F[basis, sample]);
				}
			}
			this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone = true;
			this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfBases and numberOfSignals</summary>
		private void Changed_numberOfBases_numberOfSignals()
		{
			if (this.Changed_numberOfBases_numberOfSignals_isDone) {
				return ;
			}
			this.coefficientPrecisions_F_reduced = default(Gamma);
			if (this.numberOfSignals>0) {
				if (this.numberOfBases>0) {
					this.coefficientPrecisions_F_reduced = Gamma.Uniform();
				}
			}
			// Create array for 'coefficientPrecisions_use' Backwards messages.
			this.coefficientPrecisions_use_B = new DistributionStructArray2D<Gamma,double>(this.numberOfSignals, this.numberOfBases);
			// Create array for 'coefficientPrecisions_marginal' Forwards messages.
			this.coefficientPrecisions_marginal_F = new DistributionStructArray2D<Gamma,double>(this.numberOfSignals, this.numberOfBases);
			// Create array for 'coefficients' Forwards messages.
			this.coefficients_F = new DistributionStructArray2D<Gaussian,double>(this.numberOfSignals, this.numberOfBases);
			// Create array for 'coefficients_use' Backwards messages.
			this.coefficients_use_B = new DistributionStructArray2D<Gaussian,double>(this.numberOfSignals, this.numberOfBases);
			// Create array for 'coefficients_marginal' Forwards messages.
			this.coefficients_marginal_F = new DistributionStructArray2D<Gaussian,double>(this.numberOfSignals, this.numberOfBases);
			this.Changed_numberOfBases_numberOfSignals_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfBases and signalWidth</summary>
		private void Changed_numberOfBases_signalWidth()
		{
			if (this.Changed_numberOfBases_signalWidth_isDone) {
				return ;
			}
			this.dictionaryMeans_F_reduced = default(Gaussian);
			if (this.numberOfBases>0) {
				if (this.signalWidth>0) {
					// Message to 'dictionaryMeans' from GaussianFromMeanAndVariance factor
					this.dictionaryMeans_F_reduced = GaussianFromMeanAndVarianceOp.SampleAverageLogarithm(0.0, 1.0);
				}
			}
			this.dictionaryPrecisions_F_reduced = default(Gamma);
			if (this.numberOfBases>0) {
				if (this.signalWidth>0) {
					// Message to 'dictionaryPrecisions' from GammaFromShapeAndRate factor
					this.dictionaryPrecisions_F_reduced = GammaFromShapeAndRateOpBase.SampleAverageLogarithm(1.0, 0.10000000000000001);
				}
			}
			// Create array for 'dictionaryPrecisions_use' Backwards messages.
			this.dictionaryPrecisions_use_B = new DistributionStructArray2D<Gamma,double>(this.numberOfBases, this.signalWidth);
			// Create array for 'dictionaryPrecisions_marginal' Forwards messages.
			this.dictionaryPrecisions_marginal_F = new DistributionStructArray2D<Gamma,double>(this.numberOfBases, this.signalWidth);
			for(int basis = 0; basis<this.numberOfBases; basis++) {
				// Create array for 'dictionaryMeans_use' Backwards messages.
				this.dictionaryMeans_use_B[basis] = new DistributionStructArray<Gaussian,double>(this.signalWidth);
				// Create array for 'dictionaryMeans_marginal' Forwards messages.
				this.dictionaryMeans_marginal_F[basis] = new DistributionStructArray<Gaussian,double>(this.signalWidth);
			}
			// Create array for 'dictionary' Forwards messages.
			this.dictionary_F = new DistributionStructArray2D<Gaussian,double>(this.numberOfBases, this.signalWidth);
			// Create array for 'dictionary_use' Backwards messages.
			this.dictionary_use_B = new DistributionStructArray2D<Gaussian,double>(this.numberOfBases, this.signalWidth);
			// Create array for 'dictionary_marginal' Forwards messages.
			this.dictionary_marginal_F = new DistributionStructArray2D<Gaussian,double>(this.numberOfBases, this.signalWidth);
			this.Changed_numberOfBases_signalWidth_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to a and b and noisePrecisionPrior and numberOfBases and numberOfSignals and signals and signalWidth</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised)) {
				return ;
			}
			this.noisePrecision_marginal_F = Gamma.Uniform();
			this.noisePrecision_use_B = Gamma.Uniform();
			this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and numberOfSignals and signalWidth and must reset on changes to a and b and noisePrecisionPrior and numberOfBases and signals</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised)) {
				return ;
			}
			for(int _ind0 = 0; _ind0<this.numberOfSignals; _ind0++) {
				for(int _ind1 = 0; _ind1<this.signalWidth; _ind1++) {
					this.clean_B[_ind0, _ind1] = Gaussian.Uniform();
				}
			}
			this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone = true;
			this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfSignals and signalWidth</summary>
		private void Changed_numberOfSignals_signalWidth()
		{
			if (this.Changed_numberOfSignals_signalWidth_isDone) {
				return ;
			}
			// Create array for 'clean' Backwards messages.
			this.clean_B = new DistributionStructArray2D<Gaussian,double>(this.numberOfSignals, this.signalWidth);
			this.Changed_numberOfSignals_signalWidth_isDone = true;
		}

		/// <summary>
		/// Returns the marginal distribution for 'coefficients' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray2D<Gaussian,double> CoefficientsMarginal()
		{
			return ArrayHelper.MakeCopy<DistributionStructArray2D<Gaussian,double>>(this.coefficients_marginal_F);
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.Constant_isDone = true;
		}

		/// <summary>
		/// Returns the marginal distribution for 'dictionaryMeans' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> DictionaryMeansMarginal()
		{
			return ArrayHelper.MakeCopy<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>>(this.dictionaryMeans_marginal_F);
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7_isDone = false;
					this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12_isDone = false;
					this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3_isDone = false;
					this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0_isDone = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11_isDone = false;
					this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13_isDone = false;
				}
				this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth_isDone = false;
			}
			this.Constant();
			this.Changed_numberOfSignals_signalWidth();
			this.Changed_numberOfIterationsDecreased_numberOfSignals_signalWidth_Init_a_b_noisePrecisionPrior_numberO9(initialise);
			this.Changed_numberOfBases_numberOfSignals();
			this.Changed_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_a_b_noisePrecisionPrior_signa7(initialise);
			this.Changed_a_b_numberOfBases_numberOfSignals();
			this.Changed_a_b_numberOfBases_numberOfIterationsDecreased_numberOfSignals_Init_noisePrecisionPrior_signa12(initialise);
			this.Changed_numberOfBases();
			this.Changed_numberOfBases_signalWidth();
			this.Changed_numberOfBases_numberOfIterationsDecreased_signalWidth_Init_a_b_noisePrecisionPrior_numberOfS3(initialise);
			this.Changed_numberOfIterationsDecreased_Init_a_b_noisePrecisionPrior_numberOfBases_numberOfSignals_signa0(initialise);
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_Init_a_b_numberOfBases_numberOfSignals_signa11(initialise);
			this.Changed_noisePrecisionPrior_numberOfIterationsDecreased_numberOfSignals_signals_signalWidth_Init_a_b13(initialise);
			this.Changed_a_b_noisePrecisionPrior_numberOfBases_numberOfIterations_numberOfSignals_signals_signalWidth(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="numberOfSignals") {
				return this.numberOfSignals;
			}
			if (variableName=="numberOfBases") {
				return this.numberOfBases;
			}
			if (variableName=="signalWidth") {
				return this.signalWidth;
			}
			if (variableName=="a") {
				return this.a;
			}
			if (variableName=="b") {
				return this.b;
			}
			if (variableName=="noisePrecisionPrior") {
				return this.noisePrecisionPrior;
			}
			if (variableName=="signals") {
				return this.signals;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="noisePrecision") {
				return this.NoisePrecisionMarginal();
			}
			if (variableName=="dictionaryMeans") {
				return this.DictionaryMeansMarginal();
			}
			if (variableName=="coefficients") {
				return this.CoefficientsMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>
		/// Returns the marginal distribution for 'noisePrecision' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gamma NoisePrecisionMarginal()
		{
			return this.noisePrecision_marginal_F;
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="numberOfSignals") {
				this.numberOfSignals = (int)value;
				return ;
			}
			if (variableName=="numberOfBases") {
				this.numberOfBases = (int)value;
				return ;
			}
			if (variableName=="signalWidth") {
				this.signalWidth = (int)value;
				return ;
			}
			if (variableName=="a") {
				this.a = (double)value;
				return ;
			}
			if (variableName=="b") {
				this.b = (double)value;
				return ;
			}
			if (variableName=="noisePrecisionPrior") {
				this.noisePrecisionPrior = (Gamma)value;
				return ;
			}
			if (variableName=="signals") {
				this.signals = (double[,])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
